### PR TITLE
Updated file paths to use pathlib.Path instance

### LINKED ISSUE #1534: use pathlib.Path to represent file system paths instead of strings
throughout the codebase, replace string type variables with pathlib.Path type variables that represent file system paths. these objects have convenient methods/properties for common operations, as well as make clear how the data should be used (as a file system path, not a string to display to the user, or whatever).

### PR DESCRIPTION
**Pull request by Aayush-Goel-04**
Closes #1534.
Follows up closed PR #1583.

### Checklist

- [ ] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

### CODE REVIEW

**Comment by Aayush-Goel-04** [comment]
Also please have a look at https://github.com/mandiant/capa-testfiles/pull/193

**Comment by williballenthin** [comment]
can't wait to review this in the morning, thank you @Aayush-Goel-04!

**Comment by Aayush-Goel-04** [comment]
When I run`pre-commit run flake8` on my machine it doesn't show any errors but here in CI checks it shows
```
capa/ida/plugin/form.py:602:34: G002 Logging statement uses '%'
capa/main.py:437:21: B009 Do not call getattr with a constant attribute value, it is not any safer than normal property access.
capa/main.py:580:47: C408 Unnecessary list call - rewrite as a literal.
scripts/lint.py:358:[17](https://github.com/mandiant/capa/actions/runs/5512791862/jobs/10050063810?pr=1623#step:8:18): G[20](https://github.com/mandiant/capa/actions/runs/5512791862/jobs/10050063810?pr=1623#step:8:21)1 Logging: .exception(...) should be used instead of .error(..., exc_info=True)
scripts/lint.py:891:9: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
```
What can be the reason for this.

**Comment by Aayush-Goel-04** [comment]
I'm really sorry about the hassle caused by closing and reopening the PR. It happened because of sudden influx of commits  into the master branch, which led to merge conflicts. So, I had to ditch my previous commits and update the branch, which accidentally ended up closing the PR. I know this meant you had to go through the code review process again, and sorry for the extra work.

**Comment by williballenthin** [comment]
no worries! i regret that all those changes to master caused you extra work - i hope it didn't take too long. 

did you resolve the pre-commit issues?

**Comment by Aayush-Goel-04** [comment]
> did you resolve the pre-commit issues?

All, pre-commit for flake issue are done

**Pull request merged**
