### PR TITLE
update pinned smda version

### PR DESCRIPTION
**Pull request by mike-hunhoff**
fixes Python 10 installation failure

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]

**Comment by uckelman** [comment]
Would it be possible to get this in a release, say 3.2.1? The lack of it is causing us a problem with upgrading to Python 3.10; we install flare-capa using pip, and pip doesn't give us a way to specify a non-released version.

**Comment by mr-tz** [comment]
Yeah, we should have a release out this week.

**Comment by uckelman** [comment]
How's it going for a release? We'd appreciate a 3.2.1 with just this single change, if you could.

**Comment by williballenthin** [comment]
@uckelman  https://pypi.org/project/flare-capa/3.2.1/

**Pull request merged**
