### PR TITLE
Fix binja backend stack string detection. Re-enable binja stack strin…

### PR DESCRIPTION
**Pull request by xusheng6**
…g unit test

### Checklist

- [ ] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]
lgtm, thanks!

are you able to sign the CLA? based on my understanding, there are no surprises in it, just clarified that contributions can be used in the same spirit as the existing license.

**Comment by xusheng6** [comment]
> lgtm, thanks!
> 
> are you able to sign the CLA? based on my understanding, there are no surprises in it, just clarified that contributions can be used in the same spirit as the existing license.

Jordan tried to sign on behalf of the entire group (everyone@vecto35.com), but it does not seem to work. I triggered a rescan, but it still list me as not-signed.

**Comment by xusheng6** [comment]
@williballenthin is it possible for you to see what we are missing? We believe we have done everything correct and it is pretty much a dead end for us

**Comment by williballenthin** [comment]
ok, thanks for the background. 

the CLA process is a new thing that Google requires and i haven't had to debug it yet. i'd prefer not to bother you with it too much, because i recognize that it probably feels like busywork (at least, that's usually how i feel). 

let me look around on our side and see if we can figure out what's going on. i'll reach out with any clarifying questions. 

note that, unfortunately, i'm afk for this week so i might be a bit delaying in finishing this. github mobile from the hotel room is a marvel but not a replacement for a real dev environment!

**Comment by xusheng6** [comment]
> ok, thanks for the background.
> 
> the CLA process is a new thing that Google requires and i haven't had to debug it yet. i'd prefer not to bother you with it too much, because i recognize that it probably feels like busywork (at least, that's usually how i feel).
> 
> let me look around on our side and see if we can figure out what's going on. i'll reach out with any clarifying questions.
> 
> note that, unfortunately, i'm afk for this week so i might be a bit delaying in finishing this. github mobile from the hotel room is a marvel but not a replacement for a real dev environment!

No hurry, please take your time!

**Comment by xusheng6** [comment]
@williballenthin The CLA thing now works. In fact, after we sign the CLA, it needs to be approved by Google. And Jordan got an approval email this morning. After that, I rescan the PR and I am listed as already signed.

**Comment by williballenthin** [comment]
great to hear!

based on what i read, Google ensures that an appropriate representative signs the CLA for the company. ie, a lawyer or executive and not an intern. so, maybe that review of titles took the little extra time. 

thanks for your patience working through the process, and for the PR!

**Review by williballenthin — APPROVED** [review]

**Pull request merged**
