### PR TITLE
fix: do not trim api names that include ::

### PR DESCRIPTION
**Pull request by mike-hunhoff**
capa v7 ignores the DLL portion of API features. Unfortunately the logic that implements this created a subtle bug that breaks matching for `.NET` `api` features e.g. `System.Convert::FromBase64String`. This PR updates the `trim_dll_part` function to fix the bug. 

### Checklist

- [X] No CHANGELOG update needed

- [ ] No new tests needed

- [X] No documentation update needed

### CODE REVIEW

**Comment by williballenthin** [comment]
would you consider adding a test for this? 

the routine you're updating is starting to look a little complicated, so maybe soon it's time to attempt to refactor, but without tests, i wouldn't be comfortable. even one trivial test would encode the special case/scenario that you encountered.

**Review by mr-tz — COMMENTED** [review]
Ugh, my bad. This is a pretty crucial step so I should have created more tests to prove it's working for all cases. Maybe we should add different trim/symbol generation functions for .NET vs. native vs. others.

**Comment by mr-tz** [comment]
Added an issue to track the potentially larger refactor. I think we can merge here with a test that shows the handling of the encountered case.

**Comment by mike-hunhoff** [comment]
@williballenthin @mr-tz I've added a simple to test to cover this specific case. I'd agree that a larger refactor may be needed here as now mentioned in #1899.

**Review by mr-tz — APPROVED** [review]
LGTM

**Pull request merged**
