### PR TITLE
Update utils.py

### LINKED ISSUE #1384: Highlighted (colored) text hard to read in cmd.exe (and other terminals?)
Change the colors/highlights so that output is clearly visible on black, dark, light, and white backgrounds. Use "cyan" instead of "blue", with the rational described in https://github.com/mandiant/flare-floss/pull/659.

The blue can be hard to read, green appears ok:
2023-03-15_10-17-25_cmd

2023-03-15_10-18-36_cmd

### PR DESCRIPTION
**Pull request by ggold7046**
Changed the colour/highlight to "cyan" instead of "blue" for easy noticing.

closes #1384 

### Checklist

- [ ] No CHANGELOG update needed

- [x] No new tests needed

- [ ] No documentation update needed

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]
thank you @ggold7046!

**Comment by williballenthin** [comment]
would you please add a changelog entry describing for this update? then i'm happy to merge.

**Comment by ggold7046** [comment]
> would you please add a changelog entry describing for this update? then i'm happy to merge.

Hi @williballenthin , are you asking an entry in here ? ```https://github.com/mandiant/capa/blob/master/CHANGELOG.md```
Could you tell me what should I write ?

**Comment by williballenthin** [comment]
Yup, that’s the correct file. 

The existing change log should provide a lot of good examples that you can use as a guide. I would hope to see a one sentence description of your updates, why it was made, related issue link, and your handle.

**Comment by ggold7046** [comment]
I have made an entry to changelog.md file. Update CHANGELOG.md #1404

**Comment by williballenthin** [comment]
please add the changelog updates to this PR instead of opening a separate PR.

**Comment by ggold7046** [comment]
Could you please tell me how to do that ?

**Comment by williballenthin** [comment]
You can commit and push to the same branch that you used to create this PR, or via the web interface you can browse the files of this PR and use the “edit” button to update the content.

**Pull request merged**
