### PR TITLE
update github workflows to use latest version of checkout and setup-python

### LINKED ISSUE #1967: Update deprecated checkout Actions
see warnings in current Actions
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### PR DESCRIPTION
**Pull request by sjha2048**
### Checklist

closes #1967

- [ ] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

### CODE REVIEW

**Review by mr-tz — COMMENTED** [review]
great thank you! what about this release https://github.com/actions/checkout/releases/tag/v4.1.1?

could you also update the setup-python action, see the annotations/warnings, e.g. here: https://github.com/mandiant/capa/actions/runs/8001733292

**Comment by mr-tz** [comment]
Thanks, see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

> Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload. When selecting a SHA, you should verify it is from the action's repository and not a repository fork.

**Comment by sjha2048** [comment]
TIL! 
Thanks, will update shortly.

**Comment by mr-tz** [comment]
Thanks, there's still a few to fix in the build and CI workflows. Let me know if you want to fix them as well or if we should track them separately.

**Comment by sjha2048** [comment]
works for me either way, can you help me in listing them?
I'll also go though the logs, if there are too many changes then I'll raise separate PRs

**Comment by mr-tz** [comment]
Screenshot 2024-02-22 9 58 00 PM
Screenshot 2024-02-22 9 57 51 PM

**Comment by sjha2048** [comment]
@mr-tz I have updated these actions.

**Review by mr-tz — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
