### PR TITLE
only show first lib match to reduce vverbose output noise

### LINKED ISSUE #1174: render: do not display lib rules (or make display optional)
We no longer filter library rules when rendering vverbose. This can be problematic because some library rules can have many matches, polluting the output and in some cases making it unreadable e.g.

```
...
contain loop (530 matches)
namespace
author     moritz.raabe@mandiant.com
scope      function
...
```

and

```
...
contain loop (7054 matches)
namespace
author     moritz.raabe@mandiant.com
scope      function
...
```

This is also problematic for capa explorer when trying to display, e.g. 7,054 rule matches, in a GUI.

Proposed alternatives:
- Do not display `lib` rule matches (as before)
- Make it optional to display `lib` rule matches (off by default)

The following code supports rendering all rule matches, including `lib` rules.

https://github.com/mandiant/capa/blob/5960f51f130284359de00eaedf1466da7dedb59b/capa/render/vverbose.py#L225-L233

### PR DESCRIPTION
**Pull request by mr-tz**
closes #1174

results in
WindowsTerminal_I7o39CRQF2

### Checklist

- [ ] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

### CODE REVIEW

**Comment by williballenthin** [comment]
overall, i think this is a great solution!

some nits about wording and rendering...

image
there's only one match, so the comment isn't very relevant

does a typical user know what a "lib" is and how its relevant? could we get away with not actually referencing "lib"? e.g.:

```
open process (3 matches, only showing first)
...
```

we should not display the "namespace" row for lib rules

**Comment by mr-tz** [comment]
Great points, I'll address these.

**Comment by mr-tz** [comment]
How about this?
WindowsTerminal_zi0OTkuGL8

**Comment by williballenthin** [comment]
beautiful

**Comment by mr-tz** [comment]
now looks like this:
WindowsTerminal_I7o39CRQF2

**Review by williballenthin — APPROVED** [review]

**Pull request merged**
