### PR TITLE
fix: set and parse version string

### LINKED ISSUE #1169: main: unhandled exception while processing InvalidRule exception
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1197, in <module>
  File "main.py", line 1038, in main
  File "version.py", line 5, in get_major_version
ValueError: invalid literal for int() with base 10: 'v4'
[1808] Failed to execute script 'main' due to unhandled exception!
```

likely cause is https://github.com/mandiant/capa/blob/3c1cd67f60afaed9d47565f056d76031cadecaec/.github/pyinstaller/pyinstaller.spec#L15-L32

output of GitHub command used above on Linux:

```
v4.0.1-88-g99cb5ab
```

### PR DESCRIPTION
**Pull request by mr-tz**
closes #1169

### Checklist

- [ ] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

### CODE REVIEW

**Review by mike-hunhoff — COMMENTED** [review]
Should we fully strip the version returned? e.g. on Linux the command we use returns `v4.0.1-88-g99cb5ab` meaning we set the `__version__` to `4.0.1-88-g99cb5ab` whereas we expect the format `<major>.<minor>.<patch>`. This doesn't currently break the code but could cause issues in the future if any code assumes the latter format.

**Comment by mike-hunhoff** [comment]
I've already been confused by this because what we see in `version.py` isn't the same value that makes it into `PyInstaller`.

**Comment by mr-tz** [comment]
I think this is an artifact from when we used nightly builds, so we knew which exact commit was run.
I still like it for that, but can see the confusion it causes. You think we should just use `4.0.1`, e.g.?

**Comment by mike-hunhoff** [comment]
> I think this is an artifact from when we used nightly builds, so we knew which exact commit was run. I still like it for that, but can see the confusion it causes. You think we should just use `4.0.1`, e.g.?

I think the value that we write at build should match the value we set in source:
https://github.com/mandiant/capa/blob/3c1cd67f60afaed9d47565f056d76031cadecaec/capa/version.py#L1

**Comment by mr-tz** [comment]
So, we just remove all this?

https://github.com/mandiant/capa/blob/3c1cd67f60afaed9d47565f056d76031cadecaec/.github/pyinstaller/pyinstaller.spec#L9-L32

**Review by mike-hunhoff — APPROVED** [review]
looks great, LGTM!

**Pull request merged**
