### PR TITLE
Update insn.py

### PR DESCRIPTION
**Pull request by ggold7046**
Updated with f strings for enhanced readability.

### Checklist

- [x] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]
thank you!

**Comment by ggold7046** [comment]
Hi @williballenthin , is there any other easy issue there like these ones ? I want to apply to this project for gsoc'23. What should I do to be considered for this project ?

**Comment by williballenthin** [comment]
please see our guidance here: https://github.com/mandiant/flare-gsoc-2023/blob/main/doc/contributor-guidance.md

one thing to note, as mentioned in the guidance, is that more than one contribution to our projects before GSoC doesn't award any more points. we use the initial contribution just to gauge communication style, ability to receive feedback, etc.  *not* as a way to show effort.

so, you're welcomed to take a look at the other open issues and find something that you enjoy, but also don't feel any pressure from us.

also, please don't hesitate to reach out on GH discussions or via email if you'd like to discuss potential projects further.

**Comment by ggold7046** [comment]
Hi @williballenthin , I read the "FLARE @ Google Summer of Code 2023 project ideas". When should I start drafting my application, as 20th march is approaching ?  
I have a query .....  there are many projects which shares commonalities among them. Can I apply to more than one project or I am supposed to apply to any one project ?

**Pull request merged**
