### PR TITLE
rules: use Scope enum instead of constants

### PR DESCRIPTION
**Pull request by williballenthin**
this PR updates code across capa to prefer to use `Scope.FOO` instead of `FOO_SCOPE`. before, we had two ways of doing things. now we have one. preferring to use the enum is better because it lets type checkers reason about the set of values, rather than arbitrary strings.

### Checklist

- [ ] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

### CODE REVIEW

**Review by mr-tz — APPROVED** [review]
LGTM, thank you!

edit: well, tests disagree... :)

**Comment by williballenthin** [comment]
i think the test failures are in the base branch, too

**Review by yelhamer — APPROVED** [review]
LGTM! Thanks!

Do you think there would be any confusion/mix-up regarding the `Scopes` and `Scope` classes? Should we rename `Scopes` to maybe `RuleScopes`?

As for the tests, they are failing due to some result document adjustments I believe... I'll work on that and try to get them green again.

**Comment by williballenthin** [comment]
i could see that someone might temporarily mix up Scope and Scopes, but mypy should be able to highlight the differences pretty quickly, since they have different shapes. i don't have a strong feeling either way.

**Comment by yelhamer** [comment]
I see. Let's stick to this (what you proposed in this PR) instead then. I'll merge.

**Pull request merged**
