### PR TITLE
Update to Python 3.9 and remove 3.8 support

### PR DESCRIPTION
**Pull request by Bhairvi23**
### Checklist

- [ ] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

### CODE REVIEW

**Comment by mr-tz** [comment]
Hey @Bhairvi23, do you want to work on the remaining updates needed for this? Including updating the CI and all code/documentation references to Python 3.8?

**Comment by williballenthin** [comment]
Python 3.8 receives security bug fixes through October of this year. Should we keep support through then or remove support earlier?

https://endoflife.date/python

**Comment by mr-tz** [comment]
Various other projects / dependencies seem to have moved on already - I'm fine either way though.

**Comment by williballenthin** [comment]
python 3.10 has some nice new syntax features that i look forward to using. i'm not sure how requiring 3.9 or 3.10 will affect our users. the conservative thing to do would be to keep 3.8 support until that is fully EOL'd.

**Comment by Bhairvi23** [comment]
> Hey @Bhairvi23, do you want to work on the remaining updates needed for this? Including updating the CI and all code/documentation references to Python 3.8?

Yes definitely!

**Comment by williballenthin** [comment]
lets keep 3.8 around until it goes EOL. then we can reopen and let @Bhairvi23 get this merge.

**Pull request closed without merging**
