### PR TITLE
code style: update lint.py

### PR DESCRIPTION
**Pull request by manasghandat**
Changed lint.py to use fstrings consistently. 

### Checklist

- [x] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]
this looks great, thank you!

**Comment by williballenthin** [comment]
please fix the black code style violations identified by CI, then we can merge

https://github.com/mandiant/capa/actions/runs/4365366205/jobs/7635007299

**Comment by manasghandat** [comment]
Added the correct formatting which was required

**Review by mr-tz — APPROVED** [review]
thanks!

**Pull request merged**
